project:
  type: website
  output-dir: docs

website:
  title: "dsan5000-first-site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - results.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true



